### ISSUE TITLE
Improved Output / Error Messages

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/twilio-run#26]
- [x] Improve message when build fails #24 
- [x] Show more help when commands are being executed in the wrong directory
- [x] Update message for wrong Node.js version #22 
- [x] Fix existing service message for plugins #16 
- [x] Space out pretty list output 
- [x] Improve error message in `activate` for missing serviceSid #30
